### ISSUE TITLE
ENH: n_jobs support for MultitaskLassoCv and LogregCV

### ISSUE THREAD

**Issue by mathurinm** [mathurinm/celer#119]
it does not seem that sklearn handles parallelism for multitasklassoCV

**Comment by agramfort** [comment]
it's not using it internally? did you check ?

>

**Comment by mathurinm** [comment]
my bad, I was looking at MultiTaskLasso instead of ...CV.
Implementing it in celer should be straightforward

**Comment by agramfort** [comment]
I did it in my branch for MultiTaskLassoCV. It should already be in master

>

**Comment by mathurinm** [comment]
I don't get it.

**Comment by agramfort** [comment]
https://github.com/mathurinm/celer/blob/master/celer/dropin_sklearn.py#L524

>

**Comment by mathurinm** [comment]
Ah, ok ! And since we don't have LogregCV yet, I'll close. Thank you Alex
