### ISSUE TITLE
Do you have comparative analysis vs GBM

### ISSUE THREAD

**Issue by Sandy4321** [mathurinm/celer#124]
Do you have comparative analysis vs GBM
For example lightGBM

**Comment by mathurinm** [comment]
Hello @Sandy4321, I am not sure what you mean by comparative analysis.
In any case, a comparison between these two models seems out of scope of this repo, where the focus is on fast and sklearn compatible solvers for L1 type problems (Lasso, sparse logistic regression, etc)
