### ISSUE TITLE
set_prios has a hard coded value for most relevant features

### ISSUE THREAD

**Issue by josephsalmon** [mathurinm/celer#147]
Indeed in 
https://github.com/mathurinm/celer/blob/f629c86d6db813cb050ad96485d9e8fc92e737fc/celer/cython_utils.pyx#
`prios[j] = 10000`

Should this be
`prios[j] = np.infty` or something like that?

**Comment by mathurinm** [comment]
(it's for less relevant features)   `from numpy.math cimport INFINITY` may do it
