### ISSUE TITLE
`make_correlated_data` has not a deterministic output

### ISSUE THREAD

**Issue by QB3** [mathurinm/celer#184]
When a random_state is passed to `make_correlated_data` the output of the design matrix `X` is deterministic, but not output of the observation `y`. Here is a simple code to reproduce the bug.

`from celer.datasets.simulated import make_correlated_data`
`y = make_correlated_data(10, 10, random_state=42)[1]`
`print("y.sum() = %5f " % y.sum())`
`y = make_correlated_data(10, 10, random_state=42)[1]`
`print("y.sum() = %5f " % y.sum())`

**Comment by mathurinm** [comment]
Thanks, it was fixed in master only recently: I used np.random instead of the rng that is instanciated with the seed
