### ISSUE TITLE
Turn print statement into a warning

### ISSUE THREAD

**Issue by jolars** [mathurinm/celer#239]
Please consider turning this print statement into a warning (that can be filtered out via `warnings.filterwarnings()`):

https://github.com/mathurinm/celer/blob/83c46284b712c42d499044ab4ef29e4fe2a0df63/celer/lasso_fast.pyx#L357-L358

**Comment by mathurinm** [comment]
I agree it would be way better to raise a ConvergenceWarning as we do below. Can you send a PR ?

**Comment by jolars** [comment]
Sure!
