### ISSUE TITLE
Feature request: group lasso with overlap / latent group lasso

### ISSUE THREAD

**Issue by joannagiemza** [mathurinm/celer#286]
Hello,

I am looking for python implementation of group lasso with overlap / latent group lasso. It is implemented in R (https://github.com/YaohuiZeng/grpregOverlap). It would be great if it could be a part of celer package. If you are aware of python implementations, let me know.

Best,
Joanna

**Comment by mathurinm** [comment]
Hello,
It seems that `copt` has such a solver, using a reformulation that makes it suitable for three operator splitting: http://copt.bianp.net/auto_examples/plot_overlapping_group_lasso.html

If you have a faster algorithm in mind, do not hesitate. However celer is primraly based on coordinate descent which requires block separability of the penalty, so it may not be suited to the package. We could discuss including it in the [broader `skglm` library ](github.com/scikit-learn-contrib/skglm )

**Comment by joannagiemza** [comment]
Thanks for the quick answer !

I count on the copt solver however there is an issue with the example posted. I submitted it and I hope I will have a solution soon.

Best

**Comment by mathurinm** [comment]
Did you have a look at https://github.com/CederGroupHub/sparse-lm ? they may not be as fast as celer but they seem to implement the model: https://cedergrouphub.github.io/sparse-lm/sparselm.model.html#sparselm.model.OverlapGroupLasso

**Comment by joannagiemza** [comment]
Thanks !
