### ISSUE TITLE
GroupLasso with positive=True

### ISSUE THREAD

**Issue by tomaszkacprzak** [mathurinm/celer#290]
It would be great to implement GroupLasso with a constraint for positive coefficients. Standard Lasso already implements it. Would that be possible?

**Comment by mathurinm** [comment]
Hi @tomaszkacprzak, i think it'd be doable, by adding `positive` to `dnorm_grp`, `set_prios_grp` and clipping to 0 when updating w[j] L417 of `group_fast.pyx`.

However this may be easier to implement in our new package, https://github.com/scikit-learn-contrib/skglm. Have a look at the package and if its usage fits your needs, consider opening a feature request over there; @Badr-MOUFAD maybe has time to have a look !

**Comment by mathurinm** [comment]
Implemented in skglm.
