### ISSUE TITLE
ENH: add parameter to control scaling of duality gap by norm(y)

### ISSUE THREAD

**Issue by MalcolmWolff** [mathurinm/celer#47]
To make the convergence criterion of CELER comparable with SKLearn's Lasso, it would be helpful to add a parameter which scales the duality gap by norm(y).

**Comment by mathurinm** [comment]
Thanks. I'd be glad if you could send a PR. You'd just need to scale tol inside celer_dense and celer_sparse, and add the parameter in the wrapper and in Lasso path. Make it not scale by default, and don't expose it in the Lasso and LassoCV classes: it should be for advanced users only. Sounds reasonable?

**Comment by mathurinm** [comment]
user can scale tol outside if he wants.
