### ISSUE TITLE
ENH: add LogisticRegression and LogisticRegressionCV support from sklearn

### ISSUE THREAD

**Issue by mathurinm** [mathurinm/celer#85]

**Comment by mathurinm** [comment]
@agramfort since path_function is not an attribute of sklearn.linear_model.LogisticRegression (https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/linear_model/_logistic.py#L1875), patching it is more complicated than for the Lasso case, right?

**Comment by agramfort** [comment]
for LogisticRegressionCV definitely harder. Maybe do LogisticRegression only for now?

**Comment by mathurinm** [comment]
Even for LogisticRegression only, I believe I cannot patch LogisticRegression.path (as we did for Lasso) since there is no such attribute, it is hardcoded in the Logreg.fit code 

Solution I see is to write my own `fit` method, but then I'd lose all the checks performed by sklearn's  LogisticRegression.fit()`

**Comment by agramfort** [comment]
yes you'll need to copy much more code. We can plan a refactoring in
sklearn to simplify
such inheritance mechanisms

>

**Comment by mathurinm** [comment]
Will do LogisiticRegressionCV and examples in another PR.
